sudo: required
services:
  - docker
before_install:
  - docker build -t pankajsa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pankajsa/docker-react yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-west-2-139635130479
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secure_access_key:
    secure: $AWS_SECRET_KEY